### ISSUE TITLE
Problème Pylinky

### ISSUE THREAD

**Issue by thetux07** [oncleben31/home-assistant-config#12]
Bonjour,
j'ai un problème avec pylinky: 
`Fri Dec 20 2019 10:00:40 GMT+0100 (heure normale d’Europe centrale)
Error while setting up platform linky_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 70, in setup_platform
    [LinkySensor(name, linky_data, peak_hours, peak_hours_cost, offpeak_hours_cost)]
  File "/config/custom_components/linky_custom/sensor.py", line 91, in __init__
    self.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 171, in update
    self._lk.monthly[0][CONSUMPTION] / self._lk.compare_month - 1
TypeError: unsupported operand type(s) for /: 'float' and 'list'`

'Détails du journal ( WARNING )
Fri Dec 20 2019 10:00:40 GMT+0100 (heure normale d’Europe centrale)
Unable to fetch Linky data (maybe due to night maintenance downtime schedule): Enedis.fr answered with an error: {'etat': {'valeur': 'erreur'}}'

je ne suis pas devellopeur j'ai essayer de me renseigner un peu partout mais rien :(
j'ai essayer d'installer manuellement le module pylinky en faisant pip3 install pylinky et j'ai remarqué qu'il se mettait dans /usr/lib/python3.7/.... et non usr/local/lib/python3.7...
apres je n'y connais rien, 
pouvez-vous m'aider ? ma config : 
`

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | Europe/Paris
version | 0.103.2
virtualenv | false

merci :)`

**Comment by oncleben31** [comment]
As tu  réessayé régulièrement. L'API est souvent en maintenance. Elle fonctionne par exemple maintenant.

**Comment by thetux07** [comment]
merci pour ta réponse ! 
oui je viens de reessayer en voyant ton message et j'ai toujours le même problème :(
`Sun Dec 22 2019 22:13:13 GMT+0100 (heure normale d’Europe centrale)
Error while setting up platform linky_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 59, in setup_platform
    linky_data.update()
  File "/config/custom_components/linky_custom/sensor.py", line 212, in update
    self._fetch_data()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 199, in _fetch_data
    (today - relativedelta(months=12)))['data']:
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 193, in get_data_per_period
    data = self._get_data(_MAP[_RESSOURCE][period_type], start, end)
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 130, in _get_data
    raise PyLinkyEnedisException("Enedis.fr answered with an error: " + str(json_output))
pylinky.exceptions.PyLinkyEnedisException: Enedis.fr answered with an error: {'etat': {'valeur': 'erreur'}}
'
`

**Comment by oncleben31** [comment]
@thetux07 est-ce toujours d'actualité ?

**Comment by thetux07** [comment]
Bonjour,
oui... :( toujours le même message et problème.
j'ai essayé de recréer un compte enedis et c'est pareil.
j'ai demandé à PirionFR et BaQs mais personne ne me répond, du coup, je fais sans...
c'est dommage

**Comment by oncleben31** [comment]
Est ce que tu arrives à faire fonctionner l'integration officielle (https://www.home-assistant.io/integrations/linky/) et ou acceder à ton historique heure par heure sur l'interface web enedis ?

**Comment by thetux07** [comment]
oui tout est depuis l'integration officiel sur l'interface enedis j'arrive également a avoir la consommation par heures, visiblement je ne suis pas le seul a avoir des problèmes avec cette custom intégration, mais vu que je ne suis pas développeur, j'ai du mal a saisir le probleme.
j'ai essayer de supprimer mon compte de le recreer mais rien y fait :(

**Comment by oncleben31** [comment]
J'ai une autre idée. Il y a peut être un conflit entre l'integration officielle et la custom integration qui utilise le même package python mais dans deux versions différentes.
Si tu désactives l'integration officielle, tu vois une différence ?

**Comment by thetux07** [comment]
du coup carrément réinstallé home assistant mis en place samba et juste mis custom_linky et c'est pareil
quelqu'un m'a répondu sur mon issue de Pirionfr https://github.com/Pirionfr/Home-AssistantConfig/issues/3 en me disant que c'est peu etre a cause du fait que je n'avais pas 1 an d'histrique de consomation et que c'est pour ca que ça pourrait ne pas marcher ?!
et tu veux, en mp, je peux te filer mes identifiants enedis pour que tu puisse voir si cela vient de mon compte et si oui pourquoi?
merci en tout cas

**Comment by oncleben31** [comment]
Je me souviens avoir testé cette intégration avant d'avoir un an, et ca fonctionnait. Je ne suis jamais vraiment rentré dans le code de cette intégration, et j'ai peu de temps à consacrer à HA en ce moment. Donc ce n'est pas moi qui vais pouvoir trouver la solution s'il faut rentrer dans le code.

**Comment by thetux07** [comment]
ok merci quand meme d'avoir pris un peu de temps

**Comment by oncleben31** [comment]
Si tu es motivé. Tu installes Visual Code Studio, tu clones le repository de Home Assitant Core sur ton PC ou Mac, Tu fais une configuration locale avec seulement le custom_linky et l'integration de debug (https://www.home-assistant.io/integrations/ptvsd/) et tu lances le debugage en mode pas à pas dans l'environnement de development sous forme de container. C'est pas si compliqué et c'est très formateur;

**Comment by thetux07** [comment]
ok je vais essayer ca merci :)

**Comment by thetux07** [comment]
bonjour,
c'est bon, j'ai résolu le problème,
c'était bien lié à l'historique, j'ai modifié la valeur month=12 est c'est ok
