### ISSUE TITLE
Découper le yaml lovelace

### ISSUE THREAD

**Issue by djtef** [oncleben31/home-assistant-config#55]
Le fichier export-lovelace.yaml est immense, ça devient difficilement lisible.
Dans le même principe que les entités, il est certainement préférable de le découper par onglet et/ou carte

**Comment by oncleben31** [comment]
Non car j'utilise un copier/coller depuis l'éditeur YAML du dashboard alors que je le gère via l'IHM.
C'est pour partager mon utilisation. Après mon IHM n'est pas vraiment une référence. Peut être qu'un jour je trouverai mieux pour partager si j'estime que mon IHM mérite de l'être.
